# Compose pour guacamole avec option d'authentification à 2 facteurs et enregistrements des connexions en video



version: "3.9"

networks:
  guacamole:
    name: guacamole_net
  guacamole_db:
    name: guacamole_db_net

services:
  guacamole: 
    image: guacamole/guacamole
    container_name: guacamole
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole_db
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: Axbioinfo40#
      TOTP_ENABLED: 'true'
      GUACAMOLE_HOME: /guacamole/guacamole_home
      GUACAMOLE_LOG_LEVEL: info
      GUACAMOLE_RECORDINGS_DIR: /guacamole/guacamole_home/recordings
      GUACAMOLE_RECORDING_NAME_TEMPLATE: "%e-%s"
      GUACAMOLE_RECORDING_INPUT_METHOD: ffmpeg
      GUACAMOLE_RECORDING_OUTPUT_FORMAT: m4v
      GUACAMOLE_RECORDING_METADATA: on
      GUACAMOLE_SKIP_IF_UNAVAILABLE: mysql
    depends_on:
      - guacd
      - guacamole_db
    ports:
      - 8888:8080/tcp
    restart: unless-stopped
    volumes:
      - /home/docker/appdata/guacamole/guacamole_home:/guacamole/guacamole_home
      - /home/docker/appdata/guacamole/recordings:/guacamole/guacamole_home/recordings
    networks:
      - guacamole
      - guacamole_db
      
  guacd:
    image: guacamole/guacd
    container_name: guacd
    volumes:
      - /home/docker/appdata/guacamole/drive:/drive:rw
    restart: unless-stopped
    networks:
      - guacamole

  guacamole_db:
    image: mariadb:10.5.8
    container_name: guacamole_db
    environment:
      MYSQL_ROOT_PASSWORD: monmotdepass
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: monmotdepass
    volumes:
      - /home/docker/appdata/guacamole/init:/docker-entrypoint-initdb.d:z
      - /home/docker/appdata/guacamole/data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - guacamole_db
